# Generated by Django 6.1.2 on 2026-10-06 18:53

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='bi-grid', help_text='Bootstrap icon class e.g. bi-shield-check', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('location', models.CharField(default='Kerala, India', max_length=100)),
                ('rating', models.IntegerField(default=5)),
                ('service_used', models.CharField(max_length=150)),
                ('review_text', models.TextField()),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Fees & Charges', 'Fees & Charges'), ('Processing & Approvals', 'Processing & Approvals'), ('Privacy & Safety', 'Privacy & Safety')], default='General', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('price', models.CharField(help_text='e.g. ₹499 / year', max_length=50)),
                ('is_popular', models.BooleanField(default=False)),
                ('features', models.TextField(help_text='One feature per line')),
                ('welcome_benefits', models.TextField(help_text='One welcome benefit per line')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category_tag', models.CharField(choices=[('Service Update', 'Service Update'), ('Important Notice', 'Important Notice'), ('Service Availability Update', 'Service Availability Update'), ('General News', 'General News')], default='Service Update', max_length=50)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on Homepage top 3 updates')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.membershipplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_summary', models.TextField()),
                ('description', models.TextField()),
                ('required_documents', models.TextField(help_text='Line separated or bullet points of required documents')),
                ('homline_charge', models.CharField(default='₹150 - ₹300', help_text='HOMline service charge', max_length=100)),
                ('third_party_fee', models.CharField(default='As per Government / Official portal rates', help_text='Third-party / Application fee', max_length=150)),
                ('processing_time', models.CharField(default='2 - 5 Working Days', max_length=100)),
                ('is_featured', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, help_text='e.g. Popular, Essential, Fast Track', max_length=50)),
                ('icon_class', models.CharField(default='bi-file-earmark-check', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.category')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(default=core.models.generate_request_id, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service_name_manual', models.CharField(blank=True, help_text='Used if custom service requested', max_length=150)),
                ('requirement_details', models.TextField()),
                ('contact_preference', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Call', 'Call'), ('Email', 'Email')], default='WhatsApp', max_length=20)),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='service_docs/%Y/%m/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Processing', 'Processing'), ('Information Required', 'Information Required'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes visible or status updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
